% Example usage for the classification of Arcene data

disp("Loading the data ...");
feaTrain = load('data/arcene_train.data');
feaTest  = load('data/arcene_valid.data');
gndTrain = load('data/arcene_train.labels');
gndTest  = load('data/arcene_valid.labels');

fea = [feaTrain;feaTest];
fea = fea - mean(fea);
fea = fea./max(std(fea),1e-12);
feaTrain = fea(1:100,:);
feaTest = fea(101:end,:);

disp("Classifying with SIGP ...");

% hyp = sigp(feaTrain,gndTrain,1,'efn','ker',...
%             'meankfn','sigp_matern32','meankpar',69.031,...
%             'covkfn','sigp_sinc','covkpar',20.685,...
%             'lambda',0.89625,...
%             'normalize',false);
% hyp = sigp(feaTrain,gndTrain,1,'efn','ker',...
%             'meankfn','sigp_rbf','meankpar',0.039312,...
%             'covkfn','sigp_sinc','covkpar', 18.506,...
%             'lambda',488.66,...
%             'normalize',false);
% hyp = sigp(feaTrain,gndTrain,1,'efn','ker',...
%     'meankfn','sigp_rbf','meankpar',0.18554,...
%     'covkfn', 'sigp_rq','covkpar',[9.8772  262.46],...
%     'lambda',6.0792,'normalize',false);
% hyp = sigp(feaTrain,gndTrain,1,'efn','lin',...
%     'meankfn','sigp_lin','meankpar',[],...
%     'covkfn', 'sigp_rbf','covkpar',0.14649,...
%     'lambda',186.88,'normalize',false);
hyp = sigp(feaTrain,gndTrain,3,'efn','ker',...
            'meankfn','sigp_rbf','meankpar',0.0011397,...
            'covkfn','sigp_rbf','covkpar',207.33,...
            'lambda',518.12,'normalize',false);
% hyp = sigp(feaTrain,gndTrain,1,'efn','ker',...
%     'meankfn','sigp_stud','meankpar',10.002,...
%     'covkfn', 'sigp_rbf','covkpar',315.06,...
%     'lambda',3.1495,'normalize',false);
% hyp = sigp(feaTrain,gndTrain,1,'efn','ker',...
%     'meankfn','sigp_matern32','meankpar',46.457,...
%     'covkfn', 'sigp_sinc','covkpar',19.36,...
%     'lambda',595.68,'normalize',false);
% hyp = sigp(feaTrain,gndTrain,1,'efn','ker',...
%     'meankfn','sigp_rbf','meankpar',28.805,...
%     'covkfn', 'sigp_sinc','covkpar',20.853,...
%     'lambda',237.96,'normalize',false);

disp("F1 score:" + num2str(F1score(sign(hyp.f(feaTest)),gndTest)));
